### ISSUE TITLE
What is the difference between colight.py and colight_pytorch_agent.py?

### ISSUE THREAD

**Issue by CorneliusDeng** [DaRL-LibSignal/LibSignal#10]
And also how to run colight? When I run it, "TypeError: __init__() missing 5 required positional arguments: 'reward_generator', 'world', 'traffic_env_conf', 'graph_setting', and 'args'"

Please

**Comment by derekmei233** [comment]
Hi CorneliusDeng,
There is no different between the two agents right now. We are implementing new agents and the pytorch_agent is the one independent of torch_geometric. I will notify you and close this branch after I have colight_pytorch_agent aligned with current torch_geometric version.
