### ISSUE TITLE
failed to run agent "ppo, ppo_pfrl, maddpg, mpgd"

### ISSUE THREAD

**Issue by luckywlj** [DaRL-LibSignal/LibSignal#15]
**Describe the bug**

I modified the agent as "ppo",  the world as "sumo", the network as "sumo4x4". The rest codes of the "run.py" remained unchanged.  When I run "run.py",  there is an error as follow:
File "/home/xxx/traffic_signal_control/DaRL/LibSignal/trainer/tsc_trainer.py", line 90, in create_agents
    agent = Registry.mapping['model_mapping'][Registry.mapping['command_mapping']['setting'].param['agent']](self.world, 0)
KeyError: 'ppo'

the similar errors occured in such agent "ppo_pfrl, maddpg, magd". 
I also test the other agents and they can operate normally.
Can you solve the problem and answer me?
Thanks a lot!

**Comment by luckywlj** [comment]
I rensigered PPOAgent into the __init__.py, but ppo failed to run. I checked the ppo.py and found that train() is empty. So I rewrite the train().In addition, II modifed it to ActorNet and CriticNet. Of course, there is error. So, can you provide a complete ppo version?

**Comment by yifan-dadada** [comment]
Hello! I encountered the same issue while using LibSignal. May I ask if you have found a solution?
![image](https://github.com/DaRL-LibSignal/LibSignal/assets/88924753/2a101b58-dd01-4d3b-bc19-a3986fd07fd1)

**Comment by xingxindrst** [comment]
> Hello! I encountered the same issue while using LibSignal. May I ask if you have found a solution?

Hello! I have the same issue. Have you solved this issue?
